### ISSUE TITLE
Recap Reminder

### ISSUE THREAD

**Issue by jcaruso001** [Project-Caruso/MessagePro#40]
Emmit says no users are getting a recap reminder

**Comment by jcaruso001** [comment]
This should be resolved.

**Comment by Emmitts89** [comment]
I still do not get any kind of notification for this, neither does Joe.

**Comment by jcaruso001** [comment]
Make sure you set a time and turn it on then save it...

![screenshot_2015-04-16-21-12-46](https://cloud.githubusercontent.com/assets/4194148/7194954/745d0f86-e47d-11e4-8a03-8ec7c835e500.png)


![screenshot_2015-04-16-21-09-24](https://cloud.githubusercontent.com/assets/4194148/7194929/2e7da4da-e47d-11e4-8a74-e0e6b10db25d.png)

**Comment by Emmitts89** [comment]
I received recap reminder

**Comment by jcaruso001** [comment]
Verified
