### ISSUE TITLE
Thread Bug

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#44]
My whole thread was deleted with Joe and I did not delete it. 

Joe sent me 20 messages in a row and I did not receive any. On his end, those 20 messages went back and forth between stating that they were sent from me and sent from him. In addition, after about 30 minutes of our testing stuff, the app just stopped sending me or him the messages that we were sending each other. I never got any of these 20 and I checked again before I went to bed and I still did not receive any. He did not receive any of the ones I sent either. The app did not provide any errors or shut down or anything, just stopped receiving messages and showing that the ones that we were sending were actually sent.

**Comment by Emmitts89** [comment]
When I opened the app, this is still an issue....some of the messages that Joe sent me were out of order and showing on my side as messages that I sent.

**Comment by Emmitts89** [comment]
/

**Comment by jcaruso001** [comment]
I believe it was out of order due to the time not being GMT from the app... I've fixed this As for being deleted, you won't get those back up let me know if it happens again/

**Comment by Emmitts89** [comment]
Thread order is still not working. If you scroll up through your thread and then down everything gets out of order and then usually stays out of order

**Comment by jcaruso001** [comment]
Thread order will not update unless new messages have been sent in every thread...

**Comment by jcaruso001** [comment]
After sending a message to everyone again it is in order.

![screenshot_2015-04-20-22-24-40](https://cloud.githubusercontent.com/assets/4194148/7245177/3b94c1f8-e7ac-11e4-9d7f-98e1eca79d5d.png)

**Comment by Emmitts89** [comment]
Main message screen is in order now.

**Comment by jcaruso001** [comment]
Verified.
